// This file has been generated by Specta. DO NOT EDIT.

import { createTauRPCProxy as createProxy, type InferCommandOutput } from 'taurpc'
type TAURI_CHANNEL<T> = (response: T) => void


/**
 * Serializable view of AppState for frontend. Excludes mpsc::Receiver and other non-serializable fields.
 */
export type AppStateDto = { library_path: string; library: Partial<{ [key in string]: Snippet[] }>; categories: string[]; selected_category: number | null; status: string; sync_url: string; sync_status: string; expansion_paused: boolean; template_date_format: string; template_time_format: string; discovery_enabled: boolean; discovery_threshold: number; discovery_lookback: number; discovery_min_len: number; discovery_max_len: number; discovery_excluded_apps: string; discovery_excluded_window_titles: string; ghost_suggestor_enabled: boolean; ghost_suggestor_debounce_ms: number; ghost_suggestor_display_secs: number; ghost_suggestor_offset_x: number; ghost_suggestor_offset_y: number; ghost_follower_enabled: boolean; ghost_follower_edge_right: boolean; ghost_follower_monitor_anchor: number; ghost_follower_search: string; ghost_follower_hover_preview: boolean; ghost_follower_collapse_delay_secs: number; clip_history_max_depth: number; script_library_run_disabled: boolean; script_library_run_allowlist: string }

/**
 * Clipboard entry DTO (Instant not serializable).
 */
export type ClipEntryDto = { content: string; process_name: string; window_title: string; length: number }

/**
 * Config update DTO. All fields optional; only provided fields are updated.
 */
export type ConfigUpdateDto = { expansion_paused: boolean | null; template_date_format: string | null; template_time_format: string | null; sync_url: string | null; discovery_enabled: boolean | null; discovery_threshold: number | null; discovery_lookback: number | null; discovery_min_len: number | null; discovery_max_len: number | null; discovery_excluded_apps: string | null; discovery_excluded_window_titles: string | null; ghost_suggestor_enabled: boolean | null; ghost_suggestor_debounce_ms: number | null; ghost_suggestor_display_secs: number | null; ghost_suggestor_offset_x: number | null; ghost_suggestor_offset_y: number | null; ghost_follower_enabled: boolean | null; ghost_follower_edge_right: boolean | null; ghost_follower_monitor_anchor: number | null; ghost_follower_search: string | null; ghost_follower_hover_preview: boolean | null; ghost_follower_collapse_delay_secs: number | null; clip_history_max_depth: number | null; script_library_run_disabled: boolean | null; script_library_run_allowlist: string | null }

/**
 * Diagnostic entry DTO for Log tab.
 */
export type DiagnosticEntryDto = { timestamp_ms: number; level: string; message: string }

/**
 * Expansion stats DTO for Analytics dashboard.
 */
export type ExpansionStatsDto = { total_expansions: number; total_chars_saved: number; estimated_time_saved_secs: number; top_triggers: ([string, number])[] }

export type GhostFollowerStateDto = { enabled: boolean; pinned: PinnedSnippetDto[]; search_filter: string; 
/**
 * Position (x, y) for edge-anchored window. None on non-Windows.
 */
position: [number, number] | null; 
/**
 * True when edge is Right (for positioner TopRight).
 */
edge_right: boolean; 
/**
 * True when monitor is Primary (positioner works best for primary).
 */
monitor_primary: boolean }

/**
 * Ghost Suggestor state for overlay.
 */
export type GhostSuggestorStateDto = { has_suggestions: boolean; suggestions: SuggestionDto[]; selected_index: number; position: [number, number] | null; 
/**
 * When true, enable mouse passthrough (e.g. when fading out per display_duration).
 */
should_passthrough: boolean }

export type InteractiveVarDto = { tag: string; label: string; var_type: string; options: string[] }

export type PendingVariableInputDto = { content: string; vars: InteractiveVarDto[]; values: Partial<{ [key in string]: string }>; choice_indices: Partial<{ [key in string]: number }>; checkbox_checked: Partial<{ [key in string]: boolean }> }

export type PinnedSnippetDto = { trigger: string; content: string; content_preview: string; category: string; snippet_idx: number }

/**
 * A text expansion snippet.
 * 
 * Matches the JSON format from text_expansion_library.json:
 * trigger, content, options, category, profile, appLock, pinned, lastModified.
 */
export type Snippet = { trigger: string; content: string; options?: string; category?: string; profile?: string; appLock?: string; pinned?: string; lastModified?: string }

export type SuggestionDto = { trigger: string; content_preview: string; category: string }

/**
 * UI preferences DTO for frontend.
 */
export type UiPrefsDto = { last_tab: number; column_order: string[] }

const ARGS_MAP = { '':'{"add_snippet":["category","snippet"],"cancel_variable_input":[],"clear_clipboard_history":[],"clear_diagnostic_logs":[],"copy_to_clipboard":["text"],"delete_clip_entry":["index"],"delete_snippet":["category","snippet_idx"],"get_app_state":[],"get_clipboard_entries":[],"get_diagnostic_logs":[],"get_expansion_stats":[],"get_ghost_follower_state":["search_filter"],"get_ghost_suggestor_state":[],"get_pending_variable_input":[],"get_script_library_js":[],"get_ui_prefs":[],"ghost_follower_insert":["trigger","content"],"ghost_follower_request_edit":["category","snippet_idx"],"ghost_follower_request_promote":["content","trigger"],"ghost_follower_request_view_full":["content"],"ghost_follower_set_search":["filter"],"ghost_follower_toggle_pin":["category","snippet_idx"],"ghost_suggestor_accept":[],"ghost_suggestor_create_snippet":[],"ghost_suggestor_cycle_forward":[],"ghost_suggestor_dismiss":[],"greet":["name"],"load_library":[],"reset_expansion_stats":[],"save_library":[],"save_script_library_js":["content"],"save_settings":[],"save_ui_prefs":["last_tab","column_order"],"set_library_path":["path"],"submit_variable_input":["values"],"update_config":["config"],"update_snippet":["category","snippet_idx","snippet"]}' }
export type Router = { "": {add_snippet: (category: string, snippet: Snippet) => Promise<null>, 
cancel_variable_input: () => Promise<null>, 
clear_clipboard_history: () => Promise<null>, 
clear_diagnostic_logs: () => Promise<null>, 
copy_to_clipboard: (text: string) => Promise<null>, 
delete_clip_entry: (index: number) => Promise<null>, 
delete_snippet: (category: string, snippetIdx: number) => Promise<null>, 
get_app_state: () => Promise<AppStateDto>, 
get_clipboard_entries: () => Promise<ClipEntryDto[]>, 
get_diagnostic_logs: () => Promise<DiagnosticEntryDto[]>, 
get_expansion_stats: () => Promise<ExpansionStatsDto>, 
get_ghost_follower_state: (searchFilter: string | null) => Promise<GhostFollowerStateDto>, 
get_ghost_suggestor_state: () => Promise<GhostSuggestorStateDto>, 
get_pending_variable_input: () => Promise<PendingVariableInputDto | null>, 
get_script_library_js: () => Promise<string>, 
get_ui_prefs: () => Promise<UiPrefsDto>, 
ghost_follower_insert: (trigger: string, content: string) => Promise<null>, 
ghost_follower_request_edit: (category: string, snippetIdx: number) => Promise<null>, 
ghost_follower_request_promote: (content: string, trigger: string) => Promise<null>, 
ghost_follower_request_view_full: (content: string) => Promise<null>, 
ghost_follower_set_search: (filter: string) => Promise<null>, 
ghost_follower_toggle_pin: (category: string, snippetIdx: number) => Promise<null>, 
ghost_suggestor_accept: () => Promise<[string, string] | null>, 
ghost_suggestor_create_snippet: () => Promise<[string, string] | null>, 
ghost_suggestor_cycle_forward: () => Promise<number>, 
ghost_suggestor_dismiss: () => Promise<null>, 
greet: (name: string) => Promise<string>, 
load_library: () => Promise<number>, 
reset_expansion_stats: () => Promise<null>, 
save_library: () => Promise<null>, 
save_script_library_js: (content: string) => Promise<null>, 
save_settings: () => Promise<null>, 
save_ui_prefs: (lastTab: number, columnOrder: string[]) => Promise<null>, 
set_library_path: (path: string) => Promise<null>, 
submit_variable_input: (values: Partial<{ [key in string]: string }>) => Promise<null>, 
update_config: (config: ConfigUpdateDto) => Promise<null>, 
update_snippet: (category: string, snippetIdx: number, snippet: Snippet) => Promise<null>} };


export const createTauRPCProxy = () => createProxy<Router>(ARGS_MAP)
export type { InferCommandOutput }
